export const workoutList = [
  {
    name: '가벼운 걷기',
    eng_name: 'slow walking',
    calories_spent_per_hour: 180,
    done: false,
    minutes: 0,
  },
  {
    name: '빠른 걷기',
    eng_name: 'fast walking',
    calories_spent_per_hour: 300,
    done: false,
    minutes: 0,
  },
  {
    name: '골프',
    eng_name: 'golf',
    calories_spent_per_hour: 270,
    done: false,
    minutes: 0,
  },
  {
    name: '배드민턴',
    eng_name: 'badminton',
    calories_spent_per_hour: 340,
    done: false,
    minutes: 0,
  },
  {
    name: '가벼운 달리기',
    eng_name: 'slow running',
    calories_spent_per_hour: 480,
    done: false,
    minutes: 0,
  },
  {
    name: '격렬한 달리기',
    eng_name: 'fast running',
    calories_spent_per_hour: 630,
    done: false,
    minutes: 0,
  },
  {
    name: '헬스',
    eng_name: 'weight training',
    calories_spent_per_hour: 500,
    done: false,
    minutes: 0,
  },
  {
    name: '등산',
    eng_name: 'climbing',
    calories_spent_per_hour: 196,
    done: false,
    minutes: 0,
  },
  {
    name: '조깅',
    eng_name: 'jogging',
    calories_spent_per_hour: 196,
    done: false,
    minutes: 0,
  },
  {
    name: '수영',
    eng_name: 'swimming',
    calories_spent_per_hour: 273,
    done: false,
    minutes: 0,
  },
  {
    name: '에어로빅',
    eng_name: 'aerobic',
    calories_spent_per_hour: 126,
    done: false,
    minutes: 0,
  },
  {
    name: '스키',
    eng_name: 'skiing',
    calories_spent_per_hour: 186,
    done: false,
    minutes: 0,
  },
  {
    name: '볼링',
    eng_name: 'bowling',
    calories_spent_per_hour: 90,
    done: false,
    minutes: 0,
  },
  {
    name: '배구',
    eng_name: 'volleyball',
    calories_spent_per_hour: 200,
    done: false,
    minutes: 0,
  },
  {
    name: '야구',
    eng_name: 'baseball',
    calories_spent_per_hour: 180,
    done: false,
    minutes: 0,
  },
  {
    name: '줄넘기',
    eng_name: 'julumki',
    calories_spent_per_hour: 224,
    done: false,
    minutes: 0,
  },
  {
    name: '테니스',
    eng_name: 'tennis',
    calories_spent_per_hour: 176,
    done: false,
    minutes: 0,
  },
  {
    name: '농구',
    eng_name: 'basketball',
    calories_spent_per_hour: 200,
    done: false,
    minutes: 0,
  },
  {
    name: '탁구',
    eng_name: 'table tennis',
    calories_spent_per_hour: 200,
    done: false,
    minutes: 0,
  },
  {
    name: '자전거타기',
    eng_name: 'bicycling',
    calories_spent_per_hour: 111,
    done: false,
    minutes: 0,
  },
];
